---
name: Fedora 42 Publish
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/fedora-42-publish.yml"
      - "fedora/42/**"

env:
  DOCKERFILE_DIR: fedora/42
  TAG: mrlesmithjr/fedora:42

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          brew install hadolint
      - name: Run pre-commit checks
        run: |
          SKIP=no-commit-to-branch pre-commit run --files ${DOCKERFILE_DIR}/**

  docker:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAG }}
