---
name: Ubuntu 24.04 Publish
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ubuntu-2404-publish.yml"
      - "ubuntu/24.04/**"

env:
  DOCKERFILE_DIR: ubuntu/24.04
  TAG: mrlesmithjr/ubuntu:24.04

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install dependencies
        run: |
          apt -y install python3-pip
          pip install -r requirements.txt -r requirements-dev.txt
          brew install hadolint
      - name: Run pre-commit checks
        run: |
          SKIP=no-commit-to-branch pre-commit run --files ${DOCKERFILE_DIR}/**

  docker:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKERFILE_DIR }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.TAG }}
